export const products = [
    {
        name: "Tarantino",
        price: 200,
        stock: 10,
        id: '1',
        category: 'Peliculas',
        img: '/assets/tarantino-movie.png',
    },
    {
        name: "Bruce Lee",
        price: 1000,
        stock: 20,
        id: '11',
        category: 'Peliculas',
        img: '/assets/bruce-movie.png',
    },
    {
        name: "Pulp Fiction",
        price: 200,
        stock: 14,
        id: '12',
        category: 'Peliculas',
        img: '/assets/pulp-movie.jpg',
    },
    {
        name: 'Coder',
        price: 300,
        stock: 4,
        id: '2',
        category: 'Programacion',
        img: '/assets/dev-program.png',
    },
    {
        name: 'Peaky Blinders',
        price: 700,
        stock: 6,
        id: '3',
        category: 'Series',
        img: '/assets/peaky-series.png',
    },
    {
        name: 'Stranger Things',
        price: 700,
        stock: 6,
        id: '9',
        category: 'Series',
        img: '/assets/stranger-series.jpg',
    },
    {
        name: 'Breaking Bad',
        price: 900,
        stock: 10,
        id: '10',
        category: 'Series',
        img: '/assets/breaking-series.jpg',
    },
    {
        name: 'Play Station',
        price: 80,
        stock: 20,
        id: '4',
        category:'Gamer',
        img: '/assets/play-gamer.png',
    },
    {
        name: 'Mortal Kombat',
        price: 808,
        stock: 10,
        id: '7',
        category:'Gamer',
        img: '/assets/mortal-gamer.png',
    },
    {
        name: 'Street Fighter',
        price: 808,
        stock: 10,
        id: '8',
        category:'Gamer',
        img: '/assets/street-gamer.png',
    },
    {
        name: 'Coder Rex',
        price: 600,
        stock: 8,
        id: '5',
        category: 'Programacion',
        img: '/assets/dev-program3.png',
    },
    {
        name: 'Coder Evolution',
        price: 800,
        stock: 8,
        id: '6',
        category: 'Programacion',
        img: '/assets/dev-program1.png',
    }
];
